---

- name: check if rustup exists
  command: which rustup
  register: result_rustup
  ignore_errors: yes
  changed_when: no
  become: no

- name: install rustup
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  when: result_rustup is failed
  become: no

- name: export PATH
  blockinfile:
    path: "{{ ansible_env.HOME }}/.profile"
    block: |
      export PATH=$PATH:{{ ansible_env.HOME }}/.cargo/bin
    create: yes
    state: "{{ shell_profile_block_default }}"
  when: result_rustup is failed
  become: no
  notify: source profile
