---

# NOTE: The expression of |ansible_architecture| is inconsistent (e.g. "amd64" is expressed as "x86_64"), so I don't use it.
- name: get architecture for apt
  command: dpkg --print-architecture
  register: __dpkg_print_arch
  become: no
  changed_when: no
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: set variable for arch
  set_fact:
    var_arch_for_dpkg: "{{ __dpkg_print_arch.stdout if __dpkg_print_arch is defined else ansible_architecture }}"
  become: no
  changed_when: no

- name: add apt key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
  become: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: add apt repository
  apt_repository:
    repo: "deb [arch={{ var_arch_for_dpkg }}] https://packages.microsoft.com/repos/vscode stable main"
  become: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: apt install
  apt:
    name:
      - code
    state: present
  become: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: get existing vscode extensions
  command: code --list-extensions
  register: __vscode_list_ext
  become: no
  changed_when: no
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: set variable for vscode extensions
  set_fact:
    vscode_list_ext: "{{ __vscode_list_ext.stdout if __vscode_list_ext is defined else '' }}"
  become: no
  changed_when: no

- name: install vscode extensions
  command: "code --install-extension {{ item }}"
  become: no
  when: "{{ item }} not in vscode_list_ext"
  loop:
    - austin.code-gnu-global
    - cschlosser.doxdocgen
    - DavidAnson.vscode-markdownlint
    - donjayamanne.python-environment-manager
    - donjayamanne.python-extension-pack
    - eamodio.gitlens
    - EditorConfig.EditorConfig
    - GitHub.vscode-pull-request-github
    - golang.go
    - haskell.haskell
    - jeff-hykin.better-cpp-syntax
    - justusadam.language-haskell
    - KevinRose.vsc-python-indent
    - matklad.rust-analyzer
    - maziac.asm-code-lens
    - ms-azuretools.vscode-docker
    - MS-CEINTL.vscode-language-pack-ja
    - ms-dotnettools.csharp
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-vscode-remote.remote-containers
    - ms-vscode-remote.remote-ssh
    - ms-vscode-remote.remote-ssh-edit
    - ms-vscode-remote.remote-wsl
    - ms-vscode.cpptools
    - ms-vscode.cpptools-extension-pack
    - ms-vscode.cpptools-themes
    - ms-vscode.hexeditor
    - njpwerner.autodocstring
    - pradip.replace-selected
    - quantum.quantum-devkit-vscode
    - sergey-kintsel.haskell-formatter-vscode-extension
    - tuttieee.emacs-mcx
    - wholroyd.jinja
    - yzane.markdown-pdf
    - yzhang.markdown-all-in-one

- name: copy config
  copy:
    src: settings.json
    dest: "{{ ansible_env.HOME }}/.config/Code/User/"
    mode: u=rw,g=rw,o=r
  become: no
  when: ansible_system == "Linux"
