# How to write: https://github.com/xremap/xremap/blob/v0.14.14/README.md#Configuration
modmap:
  - name: turn useless into functional
    remap:
      KEY_CAPSLOCK: KEY_LEFTCTRL
      KEY_MUHENKAN: [SUPER_L, SUPER_R]
      KEY_HENKAN: KEY_RIGHTALT
      KEY_KATAKANAHIRAGANA: KEY_RIGHTALT

keymap:
  - name: add arrow keybinds
    remap:
      SUPER_L-SUPER_R-KEY_I: KEY_UP
      SUPER_L-SUPER_R-KEY_K: KEY_DOWN
      SUPER_L-SUPER_R-KEY_J: KEY_LEFT
      SUPER_L-SUPER_R-KEY_L: KEY_RIGHT
      SUPER_L-SUPER_R-KEY_O: KEY_BACKSPACE
      SUPER_L-SUPER_R-KEY_M: KEY_DELETE
