---

- name: get desktop environment
  shell: echo "$XDG_CURRENT_DESKTOP"
  register: xdg_current_desktop
  become: no
  changed_when: no

- name: check desktop environment
  meta: end_play
  when: "GNOME" not in xdg_current_desktop.stdout

- name: apt install
  apt:
    name:
      - gnome-tweaks
    state: "{{ apt_pkg_state_default }}"
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time_default }}"
  become: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
