---

- name: add apt repository
  apt_repository:
    repo: ppa:git-core/ppa
  become: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: apt install
  apt:
    name:
      - git
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time_default }}"
  become: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
