---

- name: apt install (needed for pyenv)
  apt:
    name:
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
    state: "{{ apt_pkg_state_default }}"
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time_default }}"
  become: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: pip install
  pip:
    name:
      - ipython
      - jupyter
      - mypy
      - black
      - pipenv
    state: "{{ pip_pkg_state_default }}"
  become: no

- name: install pyenv (git clone)
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ ansible_env.HOME }}/.pyenv"
  become: no

- name: install pyenv (export environment variables)
  blockinfile:
    path: "{{ ansible_env.HOME }}/.profile"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
    marker: "# {mark} ANSIBLE MANAGED BLOCK for .profile ; ROLE: {{ role_name }}"
    state: "{{ shell_profile_block_default }}"
  become: no
  notify: source profile
