---

- name: pip install
  pip:
    name:
      - ipython
      - jupyter
      - mypy
      - black
      - pipenv
    state: "{{ pip_pkg_state_default }}"
  become: no

- name: install pyenv (git clone)
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ ansible_env.HOME }}/.pyenv"
  become: no

- name: install pyenv (export environment variables)
  blockinfile:
    path: "{{ ansible_env.HOME }}/.profile"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
    marker: "# {mark} ANSIBLE MANAGED BLOCK for .profile ; ROLE: {{ role_name }}"
    state: "{{ shell_profile_block_default }}"
  become: no
  notify: source profile
