---
- name: get the latest version
  shell: >-
    wget -qO- https://api.github.com/repos/bazelbuild/bazelisk/releases/latest | grep -oP '(?<=^  "name": ")[^"]+'
  register: __version
  become: no
  changed_when: no

- name: install
  get_url:
    url: "https://github.com/bazelbuild/bazelisk/releases/download/{{ __version.stdout }}/bazelisk-linux-amd64"
    dest: "{{ binary_dir_path }}/bazelisk"
    mode: u=rx,g=rx,o=rx
    force: yes
  become: yes
  when: ansible_system == "Linux" and ansible_architecture == "x86_64"
