---

- name: check if inputrc exists
  stat:
    path: /etc/inputrc
  register: st_inputrc
  become: yes
  changed_when: false

- name: disable beep
  lineinfile:
    path: /etc/inputrc
    regexp: '^# set bell-style none'
    line: 'set bell-style none'
  become: yes
  when: st_inputrc.stat.exists

- name: apt install
  apt:
    name:
      - xterm
    state: "{{ apt_pkg_state_default }}"
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time_default }}"
  become: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: copy config
  copy:
    src: .Xresources
    dest: "{{ ansible_env.HOME }}"
    mode: u=rw,g=rw,o=r
  become: no
  notify: load config

# supposed to be equivalent to `sudo update-alternatives --config x-terminal-emulator`
- name: change default
  file: 
    src: /usr/bin/xterm
    dest: /etc/alternatives/x-terminal-emulator
    state: link
  become: yes
