---

- name: apt install
  apt:
    name:
      - xterm
    state: "{{ apt_pkg_state_default }}"
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time_default }}"
  become: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: copy config
  copy:
    src: .Xresources
    dest: "{{ ansible_env.HOME }}"
    mode: u=rw,g=rw,o=r
  become: no
  notify: load config
