---

- name: apt install
  apt:
    name:
      - python3
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time_default }}"
  become: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
