---

# NOTE: The expression of |ansible_architecture| is inconsistent (e.g. "amd64" is expressed as "x86_64"), so I don't use it.
- name: get architecture for apt
  command: dpkg --print-architecture
  register: __dpkg_print_arch
  become: no
  changed_when: no
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: set variable
  set_fact:
    var_arch_for_dpkg: "{{ __dpkg_print_arch.stdout if __dpkg_print_arch is defined else ansible_architecture }}"
    username_orig: "{{ ansible_env.USER }}"
  become: no
  changed_when: no

- name: add apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  become: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: add apt repository
  apt_repository:
    repo: "deb [arch={{ var_arch_for_dpkg }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
  become: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: apt install
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: "{{ apt_pkg_state_default }}"
  become: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: add user to group
  user:
    name: "{{ username_orig }}"
    groups: docker
    append: yes
  become: yes
  notify: restart daemon
