---

- name: apt install
  apt:
    name:
      - gpg
      - apt-transport-https
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time_default }}"
  become: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
